name: esp32 port

on:
  push:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'tools/**'
      - 'py/**'
      - 'extmod/**'
      - 'shared/**'
      - 'lib/**'
      - 'drivers/**'
      - 'ports/esp32/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_idf402:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Initialize lv_bindings submodule
        run: git submodule update --init --recursive lib/lv_bindings
      - name: Install packages
        run: source tools/ci.sh && ci_esp32_idf402_setup
      - name: Build
        run: source tools/ci.sh && ci_esp32_build
      - name: Upload bootloader
        uses: actions/upload-artifact@v3
        with:
          name: build-idf402-bootloader
          path: build-GENERIC/bootloader/bootloader.bin
      - name: Upload partition table
        uses: actions/upload-artifact@v3
        with:
          name: build-idf402-partition-table
          path: build-GENERIC/partition_table/partition-table.bin
      - name: Upload micropython
        uses: actions/upload-artifact@v3
        with:
          name: build-idf402-micropython
          path: build-GENERIC/micropython.bin

  build_idf44:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Initialize lv_bindings submodule
        run: git submodule update --init --recursive lib/lv_bindings
      - name: Install packages
        run: source tools/ci.sh && ci_esp32_idf44_setup
      - name: Build
        run: source tools/ci.sh && ci_esp32_build
      - name: Upload bootloader
        uses: actions/upload-artifact@v3
        with:
          name: build-idf44-bootloader
          path: build-GENERIC/bootloader/bootloader.bin
      - name: Upload partition table
        uses: actions/upload-artifact@v3
        with:
          name: build-idf44-partition-table
          path: build-GENERIC/partition_table/partition-table.bin
      - name: Upload micropython
        uses: actions/upload-artifact@v3
        with:
          name: build-idf44-micropython
          path: build-GENERIC/micropython.bin
